version: "2"
services:
  zookeeper:
    image: vikrammurugesan/zookeeper
    network_mode: host
    
  mesos_master:
    image: mesosphere/mesos-master:1.0.1-2.0.93.ubuntu1404
    network_mode: host
    environment:
      MESOS_ZK: zk://127.0.0.1:2181/mesos
      MESOS_HOSTNAME: 192.168.99.100
    depends_on:
      - zookeeper
      
  mesos_slave:
    image: mesosphere/mesos-slave:1.0.1-2.0.93.ubuntu1404
    network_mode: host
    environment:
      MESOS_MASTER: zk://127.0.0.1:2181/mesos
      MESOS_WORK_DIR: /tmp
      MESOS_CONTAINERIZERS: docker
      MESOS_HOSTNAME: 192.168.99.100
      MESOS_PORT: 5051
    volumes:
      - /sys/fs/cgroup:/sys/fs/cgroup
      - /var/run/docker.sock:/var/run/docker.sock
      - /usr/local/bin/docker:/usr/bin/docker
    depends_on:
      - zookeeper
      
  marathon:
    image: mesosphere/marathon:v1.1.2
    network_mode: host
    environment:
      MARATHON_MASTER: zk://127.0.0.1:2181/mesos
    depends_on:
      - zookeeper